blog/urls.py
from .views import *
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

app_name = 'blog'


urlpatterns = [
    re_path(r'^blog-list$', blog_list, name='blog_list'),
    re_path(r'^blog-details/(?P<id>\d+)$', blog_details, name='blog_details'),

]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from .views import *
from .sitemaps import StaticSitemap
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap


admin.autodiscover()

app_name = 'frontend'


sitemaps = {
 'pages': StaticSitemap,
}

urlpatterns = [
    re_path(r'^sitemap.xml/$', sitemap, {'sitemaps': sitemaps}),
    re_path(r'^$', index, name='index'),
    re_path(r'^about$', about, name='about'),
    re_path(r'^contact-us$', contact, name='contact_us'),
    re_path(r'^login$', login, name='login'),
    re_path(r'^product-list$', product_list, name='product_list'),
    re_path(r'^get-product-details$', get_product_details, name='get_product_details'),
    re_path(r'^my-account$', my_account, name='my_account'),
]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from .views import *
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

app_name = 'products'


urlpatterns = [
    re_path(r'^shop/(?P<id>\d+)$', shop_list, name='shop'),
    re_path(r'^shop-product-detail/(?P<id>\d+)$', shop_product_detail, name='shop_product_detail'),
    re_path(r'^cart-detail$', cart_details, name='cart_details'),
    re_path(r'^wishlist$', wishlist_details, name='wishlist'),
    re_path(r'^user-wishlist$', user_wishlist, name='user_wishlist'),
    re_path(r'^checkout$', checkout, name='checkout'),
    re_path(r'^rating/(?P<id>\d+)$', rating, name='rating'),
    re_path(r'^add-to-cart/(?P<id>\d+)$', add_to_cart, name='add_to_cart'),
    re_path(r'^remove-to-cart/(?P<id>\d+)$', clear_one_cart, name='remove_to_cart'),
    re_path(r'^clear-cart$', clear_cart, name='clear_cart'),
    re_path(r'^update-cart$', update_cart, name='update_cart'),
    re_path(r'^place-order$', placeOrder, name='placeorder'),
    re_path(r'^apply-code$', apply_promocode, name='apply_code'),

]
  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('accounts/',include('accounts.urls')),

]

frontend/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from PIL import Image,ImageFilter
from colorfield.fields import ColorField
from accounts.models import *
from accounts.constants import *

class Color(models.Model):
    name = models.CharField(max_length=50)
    code = ColorField()
    
    def __str__(self):
        return self.code

class Size(models.Model):
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="category/")
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=False,null=True, blank=True)


    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'tbl_category'




class SubCategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=False,null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'tbl_subcategory'

    def __str__(self):
        return self.name 


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    sku = models.CharField(max_length=100)
    sub_category = models.ForeignKey("SubCategory", on_delete=models.CASCADE)
    weight =  models.CharField(max_length=100)
    dimensions =  models.CharField(max_length=100)
    materials = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(default=10)
    price = models.PositiveIntegerField(default=300)
    discount =models.PositiveIntegerField(null=True, blank=True)
    other_info = models.CharField(max_length = 500)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    sizes = models.ManyToManyField(Size)
    # colors = models.ManyToManyField(Color)
    rating = models.PositiveIntegerField(default = 0)

    def calculate_discount_percentage(self):
        if self.price > 0:
            discount = self.price - self.discount if self.discount else 0
            return (discount / self.price) * 100
        return 0

    class Meta:
        managed = True
        db_table = 'tbl_product'

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    
    class Meta:
        managed = True
        db_table = 'tbl_product_image'

    def __str__(self):
        return self.product.name + " - " + str(self.id)


class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    
    class Meta:
        managed = True
        db_table = 'tbl_wishlist'



class Ratings(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.CharField(max_length=1000)
    rating = models.PositiveIntegerField(default=1)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    
    class Meta:
        managed = True
        db_table = 'tbl_ratings'


class Cart(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    run_time_coupan = models.PositiveIntegerField(blank=True,null=True)
    coupans = models.ForeignKey('Coupans',blank=True,null=True,on_delete=models.SET_NULL)
    gst = models.CharField(max_length = 5,default='18%')
    gst_amount =  models.CharField(max_length = 500)

    class Meta:
        managed = True
        db_table = 'tbl_cart'

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.CharField(max_length = 500)
    size = models.CharField(max_length = 500)
    color = models.CharField(max_length = 500)
    price = models.PositiveIntegerField(default=1)
    total_price = models.PositiveIntegerField(default=1)  
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
      
    class Meta:
        managed = True
        db_table = 'tbl_cart_product'

class Order(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length = 500)
    last_name = models.CharField(max_length = 500)
    email = models.CharField(max_length = 500)
    phone = models.CharField(max_length = 500)
    address = models.CharField(max_length = 500)
    state = models.CharField(max_length = 500)
    city = models.CharField(max_length = 500)
    zipcode = models.CharField(max_length = 500)
    message = models.CharField(max_length = 500)
    discounted_price = models.PositiveIntegerField(blank=True,null=True)
    grand_total = models.PositiveIntegerField(blank=True,null=True)
    
    gst = models.CharField(max_length=5,default="18%")
    gst_amount = models.CharField(max_length=5,)
    
    grand_total = models.PositiveIntegerField(blank=True,null=True)
    
    coupan = models.ForeignKey('Coupans',on_delete=models.CASCADE,blank=True,null=True)
    status = models.PositiveIntegerField(default=ADMIN,choices=ORDER_STATUS,null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)


    class Meta:
        managed = True
        db_table = 'tbl_order'


class OrderItems(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.CharField(max_length = 500)
    size = models.CharField(max_length = 500)
    price = models.PositiveIntegerField(default=1)
    total_price = models.PositiveIntegerField(default=1)

    class Meta:
        managed = True
        db_table = 'tbl_orderItems'


class Coupans(models.Model):
    name =models.CharField(max_length = 500)
    percentage = models.PositiveIntegerField(default=1)
    count = models.CharField(max_length = 500,default=0)
    expiry_days = models.PositiveIntegerField(default=1)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'tbl_coupans'


    def __str__(self):
        return self.name

frontend/views.py
from accounts.models import *
from products.models import *
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Avg , Count
from django.shortcuts import render,redirect




def index(request):
    if request.user.is_authenticated and request.user.is_superuser and (request.user.role_id == 1 ):
        return redirect('admin:index')
    else:
        try:
            wishlist_products = Wishlist.objects.filter(created_by=request.user).values_list('product', flat=True)
        except:
            wishlist_products = None
        try:
            cart_list = CartItem.objects.filter(created_by = request.user)
        except:
            cart_list = None
        rating = Ratings.objects.filter(rating__gt = 4).order_by('-id')[0:3]
        try:
            wish_list = Wishlist.objects.filter(created_by = request.user)
        except:
            wish_list = None

        all_products = Product.objects.filter().annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('id')[0:8]
        for product in all_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0


        new_products = Product.objects.filter(discount__isnull = True ).annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('-id')[0:8]
        for product in new_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0

        discounted_products =  Product.objects.filter(discount__isnull = False).annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('-id')[0:8]
        for product in discounted_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0

        shop_data = []
        category = Category.objects.all()
        for i in category:
            s_c = []
            sub_cats = SubCategory.objects.filter(category_id = i.id )
            for j in sub_cats:
                s_c.append({"name":j.name,"id":j.id})
            print(sub_cats)
            shop_data.append({
                "name":i.name,
                "id":i.id,
                "sub_cat":s_c
            })
        
        cat_id,cat_name,cat_image,cat_items=[],[],[],[]
        for cat in category:
            cat_id.append(cat.id)
            cat_name.append(cat.name)
            cat_image.append(cat.image.url)
            product = Product.objects.filter(sub_category__category = cat ).count()
            cat_items.append(product)
        print(cat_id,cat_name,cat_image,cat_items)
        data = zip(cat_id,cat_name,cat_image,cat_items)
        return render(request, 'frontend/index.html',{"data":data,"products":all_products,"new_products":new_products,
                                                    "discounted_products":discounted_products,"wish_list":wish_list,"rating":rating,
                                                    "wishlist_products":wishlist_products,"cart_list":cart_list,"shop_data":shop_data})
    
def about(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    rating = Ratings.objects.filter(rating__gt = 4).order_by('-id')[0:3]
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    return render(request, 'frontend/about.html',{"wish_list":wish_list,"rating":rating,"cart_list":cart_list,"shop_data":shop_data})

def contact(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    if request.method == "POST":
        contact = ContactUs.objects.create(name = request.POST.get("name"),
                                           email = request.POST.get("email"),
                                           message = request.POST.get("message"))
        messages.success(request, 'Thank you for you enquiry, We will get back to you soon')
        return redirect('frontend:contact_us')
        
    
    return render(request, 'frontend/contact.html',{"wish_list":wish_list,"cart_list":cart_list,"shop_data":shop_data})

def login(request):
    return render(request, 'frontend/login.html')

def product_list(request):
    return render(request, 'frontend/shop-left-sidebar.html')

def my_account(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    user = User.objects.get(id = request.user.id)
    if request.method == "POST":
        if request.POST.get("first_name"):
            user.first_name = request.POST.get("first_name")
            
        if request.POST.get("last_name"):
            user.last_name = request.POST.get("last_name")

        if request.POST.get("mobile_no"):
            user.mobile_no = request.POST.get("mobile_no")

        if request.POST.get("dob"):
            user.dob = request.POST.get("dob")
        user.save()
        messages.success(request, 'Profile updated successfully')
    return render(request, 'frontend/my-account.html',{"wish_list":wish_list,"cart_list":cart_list,"shop_data":shop_data})

def get_product_details(request, product_id):
    product = Product.objects.get(pk=product_id)
    product_data = {
        'name': product.name,
        'description': product.description,
        # Add more fields as needed
    }
    return JsonResponse(product_data)

templates/frontend/includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="robots" content="index, follow" />
    <title>Star Street - Fashoin E-Commerce Platform</title>
    <meta name="description" content="Star street - Fashoin eCommerce HTML Template" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Add site Favicon -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon/favicon.ico' %}" type="image/png">

    <!-- vendor css (Icon Font) -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/pe-icon-7-stroke.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font.awesome.css' %}" />

    <!-- plugins css (All Plugins Files) -->
    <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery-ui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins/venobox.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/flash.css' %}" />

</head>
<div class="header-to-bar"> HELLO EVERYONE! WELCOME TO STAR STREET E-COMMERCE PLATFORM </div>

<header>
    <div class="header-main sticky-nav ">
        <div class="container position-relative">
            <div class="row">
                <div class="col-auto align-self-center">
                    <div class="header-logo">
                        <a href="{% url 'frontend:index' %}"><img src="{% static 'assets/images/logo/logo1.png' %}" alt="Site Logo" style="height:100px;width:150px" ></a>
                    </div>
                </div>
                <div class="col align-self-center d-none d-lg-block">
                    <div class="main-menu">
                        <ul>
                            <li><a href="{% url 'frontend:index' %}">Home</a></li>
                            <li class="dropdown position-static"><a href="#">Shop <i
                                        class="pe-7s-angle-down"></i></a>
                                <ul class="mega-menu d-block">
                                    <li class="d-flex">
                                        {% for i in shop_data %}
                                        
                                        <ul class="d-block">

                                            <li class="title"><a href="{% url 'products:shop' i.id %}">{{i.name}}</a></li>
                                            {% for j in i.sub_cat %}
                                                <li><a href="{% url 'products:shop' i.id %}?cat={{j.id}}">{{j.name}}</a></li>
                                            {% endfor %}
                                            
                                        </ul>
                                        {% endfor %}
                                        
                                    </li>
                                    
                                </ul>
                            </li>
                            <li><a href="{% url 'blog:blog_list' %}">Blog</a></li>
                            <li><a href="{% url 'frontend:about' %}">About us</a></li>
                            <li><a href="{% url 'frontend:contact_us' %}">Contact us</a></li>
                        </ul>
                    </div>
                </div>
                <!-- Header Action Start -->
                <div class="col col-lg-auto align-self-center pl-0">
                    <div class="header-actions">
                        {% if request.user.is_authenticated and request.user.role_id == 2  %}
                            <a href="{% url 'frontend:my_account' %}" class="header-action-btn ">
                                <i class="pe-7s-user"></i>
                            </a>
                        {% else %}
                        <a href="{% url 'frontend:login' %}" class="header-action-btn login-btn" data-bs-toggle="modal"
                        data-bs-target="#loginActive">Sign In</a>
                        {% endif %}
                        
                        <a href="#offcanvas-wishlist"
                            class="header-action-btn header-action-btn-cart offcanvas-toggle pr-0">
                            <i class="pe-7s-like"></i>
                            
                                <span class="header-action-num">{% if wish_list.count > 0 %}{{wish_list.count}}{% else %}0{% endif %}</span>
                            <!-- <span class="cart-amount">€30.00</span> -->
                        </a>
                        <!-- Single Wedge End -->
                        <a href="#offcanvas-cart"
                            class="header-action-btn header-action-btn-cart offcanvas-toggle pr-0">
                            <i class="pe-7s-shopbag"></i>
                            
                                <span class="header-action-num">{% if cart_list.count > 0 %}{{cart_list.count}}{% else %} 0 {% endif %}</span>
                            
                            
                            <!-- <span class="cart-amount">€30.00</span> -->
                        </a>
                        <a href="#offcanvas-mobile-menu"
                            class="header-action-btn header-action-btn-menu offcanvas-toggle d-lg-none">
                            <i class="pe-7s-menu"></i>
                        </a>
                    </div>
                    <!-- Header Action End -->
                </div>
            </div>
        </div>
</header>
<div class="offcanvas-overlay"></div>

<!-- OffCanvas Wishlist Start -->
<div id="offcanvas-wishlist" class="offcanvas offcanvas-wishlist">
    <div class="inner">
        <div class="head">
            <span class="title">Wishlist</span>
            <button class="offcanvas-close">×</button>
        </div>
        <div class="body customScroll">
            <ul class="minicart-product-list">
                {% for i in wish_list %}
                <li>
                    {% with product_image=i.product.productimage_set.first %}
                        {% if product_image %}
                            <img style="width: 30% !important" src="{{ product_image.image.url }}" alt="Product Image">
                        {% else %}
                            <p>No images available for this product in the wishlist.</p>
                        {% endif %}
                    {% endwith %}
                    <div class="content">
                        <a href="" class="title">{{i.product.name}}</a>
                        <span class="quantity-price">1 x <span class="amount">${% if i.product.discount %}{{i.product.discount}}{% else %} {{i.product.price}}{% endif %}</span></span>
                        {% comment %} <a href="#" class="remove">×</a> {% endcomment %}
                    </div>
                </li>
                {% endfor %}
                
            </ul>
        </div>
        {% if wish_list %}
        <div class="foot">
            <div class="buttons">
                <a href="{% url 'products:user_wishlist' %}" class="btn btn-dark btn-hover-primary mt-30px">view wishlist</a>
            </div>
        </div>
        {% else %}
            <p align-center>No Items in you Wishlist<p>
        {% endif %}
    </div>
</div>
<!-- OffCanvas Wishlist End -->
<!-- OffCanvas Cart Start -->
<div id="offcanvas-cart" class="offcanvas offcanvas-cart">
    <div class="inner">
        <div class="head">
            <span class="title">Cart</span>
            <button class="offcanvas-close">×</button>
        </div>
        <div class="body customScroll">
            <ul class="minicart-product-list">
                {% for i in cart_list %}
                <li>
                    {% with product_image=i.product.productimage_set.first %}
                        {% if product_image %}
                            <a href="{% url 'products:shop_product_detail' i.product.id %}" class="image"><img src="{{ product_image.image.url }}"
                                alt="Cart product Image"></a>
                        {% else %}
                            <p>No images available for this product in the wishlist.</p>
                        {% endif %}
                    {% endwith %}
                   
                    <div class="content">
                        <a href="{" class="title">{{i.product.name}}</a>
                        <span class="quantity-price">1 x <span class="amount">${% if i.product.discount %}{{i.product.discount}}{% else %} {{i.product.price}}{% endif %}</span></span>
                        <a href="#" class="remove">×</a>
                    </div>
                </li>
                {% endfor %}
                
                
                </li>
            </ul>
        </div>
        {% if cart_list %}
        <div class="foot">
            <div class="buttons mt-30px">
                <a href="{% url 'products:cart_details' %}" class="btn btn-dark btn-hover-primary mb-30px">view cart</a>
            </div>
        </div>
        {% else %}
        <p align-center>No Items in you cart<p>
        {% endif %}
    </div>
</div>
{% if messages %}
    <div class="flash animate--drop-in-fade-out">
    {% for message in messages %}
        <div class="flash__icon">
            <i class="icon far fa-check-circle"></i>
        </div>
        
        <p class="flash__body">
            {{ message }}
        </p>
        {% endfor %}
    </div>
{% endif %}
<!-- OffCanvas Cart End -->