blog/urls.py
from .views import *
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

app_name = 'blog'


urlpatterns = [
    re_path(r'^blog-list$', blog_list, name='blog_list'),
    re_path(r'^blog-details/(?P<id>\d+)$', blog_details, name='blog_details'),

]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from .views import *
from .sitemaps import StaticSitemap
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap


admin.autodiscover()

app_name = 'frontend'


sitemaps = {
 'pages': StaticSitemap,
}

urlpatterns = [
    re_path(r'^sitemap.xml/$', sitemap, {'sitemaps': sitemaps}),
    re_path(r'^$', index, name='index'),
    re_path(r'^about$', about, name='about'),
    re_path(r'^contact-us$', contact, name='contact_us'),
    re_path(r'^login$', login, name='login'),
    re_path(r'^product-list$', product_list, name='product_list'),
    re_path(r'^get-product-details$', get_product_details, name='get_product_details'),
    re_path(r'^my-account$', my_account, name='my_account'),
]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('accounts/',include('accounts.urls')),

]

blog/models.py
from django.db import models

# Create your models here.


class Blogs(models.Model):
    title = models.CharField(max_length=255,blank=True,null=True)
    title_image = models.ImageField(upload_to='images/')
    second_image = models.ImageField(upload_to='images/')
    third_image = models.ImageField(upload_to='images/')
    first_description = models.TextField()
    second_description = models.TextField()
    seen = models.PositiveIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=False,null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'tbl_blog'

blog/views.py
from django.shortcuts import render,redirect
from .models import *
from products.models import *

def blog_list(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    blog = Blogs.objects.all().order_by("-id")[:9]
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    return render(request, 'blog/blog-grid.html',{"blogs":blog,"wish_list":wish_list,"shop_data":shop_data,"cart_list":cart_list,})


def blog_details(request,id):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    blog = Blogs.objects.get(id = id)
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    return render(request, 'blog/blog-single.html',{"blog":blog,"wish_list":wish_list,"shop_data":shop_data,"cart_list":cart_list,})

templates/blog/blog-grid.html
{% load static %}
{% include 'frontend/includes/header.html' %}
 

    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Blog Grid</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Blog Grid</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb-area end -->

    <!-- Blog Area Start -->
    <div class="blog-grid pb-100px pt-100px main-blog-page single-blog-page">
        <div class="container">
            <div class="row">
                {% for i in blogs %}
                <div class="col-lg-6 col-md-6 col-xl-4 mb-50px">
                    <div class="single-blog">
                        <div class="blog-image">
                            <a href="{% url 'blog:blog_details' i.id %}">
                                {% if  i.title_image %}
                                <img src="{{i.title_image.url}}"  class="img-responsive w-100" alt=""></a>
                                 {% else %}
                                <img class="img-fluid h-auto" src="{% static 'assets/images/default.jpg'  %}" alt="blog" />
                                {% endif %}
                        </div>
                        <div class="blog-text">
                            <div class="blog-athor-date">
                                <a class="blog-date height-shape" href="#"><i class="fa fa-calendar"
                                        aria-hidden="true"></i> {{i.created_on | date}}</a>
                                <a class="blog-mosion" href="#"><i class="fa fa-commenting" aria-hidden="true"></i> {{i.seen}}</a>
                            </div>
                            <h5 class="blog-heading"><a class="blog-heading-link"
                                    href="{% url 'blog:blog_details' i.id %}"> {{ i.title|slice:":100" }}{% if i.title|length > 100 %} ...{% endif %}</h5>

                            <p>{{ i.first_description|slice:":100" }}{% if i.first_description|length > 100 %} ...{% endif %}</p>

                            <a href="{% url 'blog:blog_details' i.id %}" class="btn btn-primary blog-btn"> Read More<i class="fa fa-arrow-right ml-5px"
                                    aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>

            <!--  Pagination Area Start -->
                <!-- div class="pro-pagination-style text-center" data-aos="fade-up" data-aos-delay="200">
                <div class="pages">
                    <ul>
                        <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-left"></i></a></li>
                        <li class="li"><a class="page-link active" href="#">1</a></li>
                        <li class="li"><a class="page-link" href="#">2</a></li>
                        <li class="li"><a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
                        </li>
                    </ul>
                </div>
            </div> -->
            <!--  Pagination Area End -->
        </div>
    </div>
    <!-- Blag Area End -->
    {% include 'frontend/includes/footer.html' %}

templates/blog/blog-single.html
{% load static %}
{% include 'frontend/includes/header.html' %}
 
    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Blog Details</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Blog Details</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb-area end -->

    <!-- Blog Area Start -->
    <div class="blog-grid pb-100px pt-100px main-blog-page single-blog-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 offset-lg-2">
                    <div class="blog-posts">
                        <div class="single-blog-post blog-grid-post">
                            <div class="blog-image single-blog" data-aos="fade-up" data-aos-delay="200">
                                {% if  blog.title_image %}
                                <img class="img-fluid h-auto" src="{{blog.title_image.url}}" alt="blog" />
                                {% else %}
                                <img class="img-fluid h-auto" src="{% static 'assets/images/default.jpg'  %}" alt="blog" />
                                {% endif %}
                            </div>
                            <div class="blog-post-content-inner mt-30px" data-aos="fade-up" data-aos-delay="400">
                                <div class="blog-athor-date">
                                    <a class="blog-date height-shape" href="#"><i class="fa fa-calendar"
                                            aria-hidden="true"></i> {{blog.created_on | date}} </a>
                                    <a class="blog-mosion" href="#"><i class="fa fa-commenting" aria-hidden="true"></i>
                                        {{i.seen}}</a>
                                </div>
                                <h4 class="blog-title">{{blog.title}}</h4>
                                <p data-aos="fade-up">
                                    {{blog.first_description}}
                                </p>
                            </div>
                            <div class="single-post-content">
                               
                               
                                <div class="image-porsion">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="image-left">
                                                {% if  blog.second_image %}
                                                <img class="img-fluid  w-100" src="{{blog.second_image.url}}" alt="">
                                                {% else %}
                                                <img class="img-fluid  w-100" src="{% static 'assets/images/default.jpg'  %}" alt="blog" />
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="image-left">
                                                {% if  blog.third_image %}
                                                <img class="img-fluid  w-100" src="{{blog.third_image.url}}" alt="">
                                                {% else %}
                                                <img class="img-fluid  w-100" src="{% static 'assets/images/default.jpg'  %}" alt="blog" />
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <p class="mt-30px">{{blog.second_description}}</p>
                            </div>
                        </div>
                        <!-- single blog post -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Blag Area End -->
    {% include 'frontend/includes/footer.html' %}