accounts/urls.py
from .views import *
from django.contrib import admin
from django.urls import re_path
from django.urls import path

admin.autodiscover()

app_name = 'accounts'

urlpatterns = [

    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogOutView.as_view(), name='logout'),
    re_path(r'^registration/$', RegistrationView.as_view(), name='registration'),
    

]

blog/urls.py
from .views import *
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

app_name = 'blog'


urlpatterns = [
    re_path(r'^blog-list$', blog_list, name='blog_list'),
    re_path(r'^blog-details/(?P<id>\d+)$', blog_details, name='blog_details'),

]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from .views import *
from .sitemaps import StaticSitemap
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap


admin.autodiscover()

app_name = 'frontend'


sitemaps = {
 'pages': StaticSitemap,
}

urlpatterns = [
    re_path(r'^sitemap.xml/$', sitemap, {'sitemaps': sitemaps}),
    re_path(r'^$', index, name='index'),
    re_path(r'^about$', about, name='about'),
    re_path(r'^contact-us$', contact, name='contact_us'),
    re_path(r'^login$', login, name='login'),
    re_path(r'^product-list$', product_list, name='product_list'),
    re_path(r'^get-product-details$', get_product_details, name='get_product_details'),
    re_path(r'^my-account$', my_account, name='my_account'),
]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
    path('blog/',include('blog.urls')),
    path('products/',include('products.urls')),
    path('accounts/',include('accounts.urls')),

]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from accounts.models import *
from products.models import *
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Avg , Count
from django.shortcuts import render,redirect




def index(request):
    if request.user.is_authenticated and request.user.is_superuser and (request.user.role_id == 1 ):
        return redirect('admin:index')
    else:
        try:
            wishlist_products = Wishlist.objects.filter(created_by=request.user).values_list('product', flat=True)
        except:
            wishlist_products = None
        try:
            cart_list = CartItem.objects.filter(created_by = request.user)
        except:
            cart_list = None
        rating = Ratings.objects.filter(rating__gt = 4).order_by('-id')[0:3]
        try:
            wish_list = Wishlist.objects.filter(created_by = request.user)
        except:
            wish_list = None

        all_products = Product.objects.filter().annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('id')[0:8]
        for product in all_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0


        new_products = Product.objects.filter(discount__isnull = True ).annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('-id')[0:8]
        for product in new_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0

        discounted_products =  Product.objects.filter(discount__isnull = False).annotate(
            rating_count=Count('ratings'),
            avg_rating=Avg('ratings__rating')
        ).order_by('-id')[0:8]
        for product in discounted_products:
            if product.avg_rating is not None:
                product.avg_rating *= 20
            else:
                product.avg_rating = 0

        shop_data = []
        category = Category.objects.all()
        for i in category:
            s_c = []
            sub_cats = SubCategory.objects.filter(category_id = i.id )
            for j in sub_cats:
                s_c.append({"name":j.name,"id":j.id})
            print(sub_cats)
            shop_data.append({
                "name":i.name,
                "id":i.id,
                "sub_cat":s_c
            })
        
        cat_id,cat_name,cat_image,cat_items=[],[],[],[]
        for cat in category:
            cat_id.append(cat.id)
            cat_name.append(cat.name)
            cat_image.append(cat.image.url)
            product = Product.objects.filter(sub_category__category = cat ).count()
            cat_items.append(product)
        print(cat_id,cat_name,cat_image,cat_items)
        data = zip(cat_id,cat_name,cat_image,cat_items)
        return render(request, 'frontend/index.html',{"data":data,"products":all_products,"new_products":new_products,
                                                    "discounted_products":discounted_products,"wish_list":wish_list,"rating":rating,
                                                    "wishlist_products":wishlist_products,"cart_list":cart_list,"shop_data":shop_data})
    
def about(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    rating = Ratings.objects.filter(rating__gt = 4).order_by('-id')[0:3]
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    return render(request, 'frontend/about.html',{"wish_list":wish_list,"rating":rating,"cart_list":cart_list,"shop_data":shop_data})

def contact(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    if request.method == "POST":
        contact = ContactUs.objects.create(name = request.POST.get("name"),
                                           email = request.POST.get("email"),
                                           message = request.POST.get("message"))
        messages.success(request, 'Thank you for you enquiry, We will get back to you soon')
        return redirect('frontend:contact_us')
        
    
    return render(request, 'frontend/contact.html',{"wish_list":wish_list,"cart_list":cart_list,"shop_data":shop_data})

def login(request):
    return render(request, 'frontend/login.html')

def product_list(request):
    return render(request, 'frontend/shop-left-sidebar.html')

def my_account(request):
    shop_data = []
    category = Category.objects.all()
    for i in category:
        s_c = []
        sub_cats = SubCategory.objects.filter(category_id = i.id )
        for j in sub_cats:
            s_c.append({"name":j.name,"id":j.id})
        print(sub_cats)
        shop_data.append({
            "name":i.name,
            "id":i.id,
            "sub_cat":s_c
        })
        
    try:
        wish_list = Wishlist.objects.filter(created_by = request.user)
    except:
        wish_list = None
    try:
        cart_list = CartItem.objects.filter(created_by = request.user)
    except:
        cart_list = None
    user = User.objects.get(id = request.user.id)
    if request.method == "POST":
        if request.POST.get("first_name"):
            user.first_name = request.POST.get("first_name")
            
        if request.POST.get("last_name"):
            user.last_name = request.POST.get("last_name")

        if request.POST.get("mobile_no"):
            user.mobile_no = request.POST.get("mobile_no")

        if request.POST.get("dob"):
            user.dob = request.POST.get("dob")
        user.save()
        messages.success(request, 'Profile updated successfully')
    return render(request, 'frontend/my-account.html',{"wish_list":wish_list,"cart_list":cart_list,"shop_data":shop_data})

def get_product_details(request, product_id):
    product = Product.objects.get(pk=product_id)
    product_data = {
        'name': product.name,
        'description': product.description,
        # Add more fields as needed
    }
    return JsonResponse(product_data)

templates/frontend/contact.html
{% load static %}
{% include 'frontend/includes/header.html' %}
<style>
    .error{
        color:red;
        margin-bottom: 10px !important;
    }
    .login-register-wrapper .login-form-container .login-register-form input {

        margin-bottom: 10px !important;
    }
</style>
    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Contact Us</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Contact Us</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>

    <!-- breadcrumb-area end -->

    <!-- Contact Area Start -->
    <div class="contact-area pt-100px pb-100px">
        <div class="container">
            <div class="contact-wrapper">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="contact-info">
                            <div class="single-contact">
                                <div class="icon-box">
                                    <img src="{% static 'assets/images/icons/4.png' %}" alt="">
                                </div>
                                <div class="info-box">
                                    <h5 class="title" >Phone:</h5>
                                    <p><a href="tel:0123456789">012 345 67 89</a></p>
                                </div>
                            </div>
                            <div class="single-contact">
                                <div class="icon-box">
                                    <img src="{% static 'assets/images/icons/5.png' %}" alt="">
                                </div>
                                <div class="info-box">
                                    <h5 class="title" >Email:</h5>
                                    <p><a href="mailto:demo@example.com">demo@example.com</a></p>
                                </div>
                            </div>
                            <div class="single-contact">
                                <div class="icon-box">
                                    <img src="{% static 'assets/images/icons/6.png' %}" alt="">
                                </div>
                                <div class="info-box">
                                    <h5 class="title" >Address:</h5>
                                    <p>Your address goes here</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-7">
                        <div class="contact-form">
                            <div class="contact-title mb-30">
                                <h2 class="title" data-aos="fade-up" data-aos-delay="200">Leave a Message</h2>
                                <p>There are many variations of passages of Lorem Ipsum available but the
                                    suffered alteration in some form.</p>
                            </div>
                            <form id="contact-page" class="contact-form-style" action="{% url 'frontend:contact_us' %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6" data-aos="fade-up" data-aos-delay="200">
                                        <input name="name" placeholder="Name*" type="text" required />
                                    </div>
                                    <div class="col-lg-6" data-aos="fade-up" data-aos-delay="200">
                                        <input name="email" placeholder="Email*" type="email"  required />
                                    </div>
                                    <div class="col-lg-12" data-aos="fade-up" data-aos-delay="200">
                                        <textarea name="message" placeholder="Your Message*" required></textarea>
                                        <button class="btn btn-primary mt-4" data-aos="fade-up" data-aos-delay="200" type="submit">Post Comment <i class="fa fa-arrow-right"></i></button>
                                    </div>
                                </div>
                            </form>
                            <p class="form-messege"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Area End -->

      <!-- map Area Start -->

      <div class="contact-map">
        <div id="mapid">
            <div class="mapouter">
                <div class="gmap_canvas">
                    <iframe id="gmap_canvas"
                        src="https://maps.google.com/maps?q=121%20King%20St%2C%20Melbourne%20VIC%203000%2C%20Australia&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    <a href="https://sites.google.com/view/maps-api-v2/mapv2"></a>
                </div>
            </div>
        </div>
    </div>
    <!-- map Area End -->
    {% include 'frontend/includes/footer.html' %}
    <script type="text/javascript">
    
        $(function() {
            $("#contact-page").validate({
                name: { 
                  name: {
                    required: true,
                    minlength: 3,
                  },
                  email: {
                    required: true,
                    minlength: 3,
                  },
                  message: {
                    required: true,
                  },
                  
                },
         
                messages: {
                  name:  {
                    required: "Enter your name",
                  },
                  email:  {
                    required: "Enter your email",
                  },
                  message:  {
                    required: "Enter your username",
                  },
                },
            });
         });
</script>

templates/frontend/login.html
{% load static %}
{% include 'frontend/includes/header.html' %}
<style>
    .error{
        color:red;
        margin-bottom: 20px !important;
    }
    .login-register-wrapper .login-form-container .login-register-form input {

        margin-bottom: 10px !important;
    }
</style>

    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Setup an account</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item active">register</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>

    <!-- breadcrumb-area end -->

    <!-- login area start -->
    <div class="login-register-area pt-100px pb-100px">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                    <div class="login-register-wrapper">
                        <div class="login-register-tab-list nav">
                            
                            <a data-bs-toggle="tab" href="#lg2">
                                <h4>register</h4>
                            </a>
                        </div>
                        <div class="tab-content">
                            
                            <div id="lg2" class="tab-pane active">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <form id="login" action="{% url 'accounts:registration' %}" method="post">
                                            {% csrf_token %}
                                            <input type="text" name="first_name" placeholder="First name" required/>
                                            <input type="text" name="last_name" placeholder="Last name" required/>
                                            <input name="email" placeholder="Email" type="email" required/>
                                            <input name="mobile_no" placeholder="Phone number" type="number" required/>
                                            <input type="password" id="password" name="password" placeholder="Password" required/>
                                            <input type="password" name="confirm_password" placeholder="Confirm Password" required/>
                                            
                                            <div class="button-box">
                                                <button type="submit"><span>Register</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    {% include 'frontend/includes/footer.html' %}



    <script type="text/javascript">
    
            $(function() {
                $("#login").validate({
                    rules: {
                      first_name: {
                        required: true,
                        minlength: 3
                      },
                      last_name: {
                        required: true,
                        minlength: 3
                      },
                      email: {
                        required: true,
                      },
                      mobile_no: {
                        required: true,
                        minlength: 10
                      },
                      password: {
                        required: true,
                        minlength: 7
                      },
                      confirm_password: {
                        required: true,
                        equalTo: "#password"
                      }
                    },
             
                    messages: {
                      first_name:  {
                        required: "Enter your first name",
                        minlength: "First name should be minimum 3 characters long"
                      },
                      last_name:  {
                        required: "Enter your last name",
                        minlength: "Last name should be minimum 3 characters long"
                      },
                      email:  {
                        required: "Enter your username",
                      },
                      mobile_no:  {
                        required: "Enter your mobile number",
                        minlength: "Mobile number should be minimum 10 characters long"
                      },
                      password:  {
                        required: "Enter your password",
                        minlength: "Password should be minimum 7 characters long"
                      },
                      confirm_password: {
                        required: "Enter your confirmation password",
                        equalTo: "Confirm password not matched! "
                      }
                    },
                });
             });
    </script>

templates/frontend/my-account.html
{% load static %}
{% include 'frontend/includes/header.html' %}
    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-12 text-center">
                    <h2 class="breadcrumb-title">Shop</h2>
                    <!-- breadcrumb-list start -->
                    <ul class="breadcrumb-list">
                        <li class="breadcrumb-item"><a href="{% url 'frontend:index' %}">Home</a></li>
                        <li class="breadcrumb-item active">Account</li>
                    </ul>
                    <!-- breadcrumb-list end -->
                </div>
            </div>
        </div>
    </div>

    <!-- breadcrumb-area end -->

    <!-- account area start -->
    <div class="account-dashboard pt-100px pb-100px">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    <!-- Nav tabs -->
                    <div class="dashboard_tab_button" data-aos="fade-up" data-aos-delay="0">
                        <ul role="tablist" class="nav flex-column dashboard-list">
                            <li><a href="#dashboard" data-bs-toggle="tab" class="nav-link active">Dashboard</a></li>
                            <li> <a href="#orders" data-bs-toggle="tab" class="nav-link">Orders</a></li>
                            {% comment %} <li><a href="#downloads" data-bs-toggle="tab" class="nav-link">Downloads</a></li> {% endcomment %}
                            {% comment %} <li><a href="#address" data-bs-toggle="tab" class="nav-link">Addresses</a></li> {% endcomment %}
                            <li><a href="#account-details" data-bs-toggle="tab" class="nav-link">Account details</a>
                            </li>
                            <li><a href="{% url 'accounts:logout' %}" class="nav-link">logout</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content" data-aos="fade-up" data-aos-delay="200">
                        <div class="tab-pane fade show active" id="dashboard">
                            <h4>Dashboard </h4>
                            <p>From your account dashboard. you can easily check &amp; view your <a href="#">recent
                                    orders</a>, manage your <a href="#">shipping and billing addresses</a> and <a
                                    href="#">Edit your password and account details.</a></p>
                        </div>
                        <div class="tab-pane fade" id="orders">
                            <h4>Orders</h4>
                            <div class="table_page table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Order</th>
                                            <th>Date</th>
                                            <th>Status</th>
                                            <th>Total</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>May 10, 2018</td>
                                            <td><span class="success">Completed</span></td>
                                            <td>$25.00 for 1 item </td>
                                            <td><a href="cart.html" class="view">view</a></td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>May 10, 2018</td>
                                            <td>Processing</td>
                                            <td>$17.00 for 1 item </td>
                                            <td><a href="cart.html" class="view">view</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="downloads">
                            <h4>Downloads</h4>
                            <div class="table_page table-responsive">
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Downloads</th>
                                            <th>Expires</th>
                                            <th>Download</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Shopnovilla - Free Real Estate PSD Template</td>
                                            <td>May 10, 2018</td>
                                            <td><span class="danger">Expired</span></td>
                                            <td><a href="#" class="view">Click Here To Download Your File</a></td>
                                        </tr>
                                        <tr>
                                            <td>Organic - ecommerce html template</td>
                                            <td>Sep 11, 2018</td>
                                            <td>Never</td>
                                            <td><a href="#" class="view">Click Here To Download Your File</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane" id="address">
                            <p>The following addresses will be used on the checkout page by default.</p>
                            <h5 class="billing-address">Billing address</h5>
                            <a href="#" class="view">Edit</a>
                            <p class="mb-2"><strong>Michael M Hoskins</strong></p>
                            <address>
                                <span class="mb-1 d-inline-block"><strong>City:</strong> Seattle</span>,
                                <br>
                                <span class="mb-1 d-inline-block"><strong>State:</strong> Washington(WA)</span>,
                                <br>
                                <span class="mb-1 d-inline-block"><strong>ZIP:</strong> 98101</span>,
                                <br>
                                <span><strong>Country:</strong> USA</span>
                            </address>
                        </div>
                        <div class="tab-pane fade" id="account-details">
                            <h3>Account details </h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form action="{% url 'frontend:my_account' %}" method="post" >
                                            {% csrf_token %}
                                            <div class="default-form-box mb-20">
                                                <label>First Name</label>
                                                <input type="text" name="first_name" value="{{request.user.first_name}}">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Last Name</label>
                                                <input type="text" name="last_name" value="{{request.user.last_name}}">
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Email</label>
                                                <input type="text" name="email" value="{{request.user.email}}" readonly>
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Phone Number</label>
                                                <input type="text" name="mobile_no" value="{{request.user.mobile_no}}" >
                                            </div>
                                            <div class="default-form-box mb-20">
                                                <label>Birthdate</label>
                                                <input type="date" name="dob" value="{{request.user.dob}}">
                                            </div>
                                            
                                            
                                            <button class="btn btn-lg btn-primary btn-hover-dark m-auto"> Update
                                             </button>
                                        
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- account area start -->
    {% include 'frontend/includes/footer.html' %}